[project]
name = "nlp-politics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepmultilingualpunctuation>=1.0.1",
    "dotenv>=0.9.9",
    "google-api>=0.1.12",
    "google-api-python-client>=2.184.0",
    "jupyter>=1.1.1",
    "nltk>=3.9.2",
    "pandas>=2.3.3",
    "praw>=7.8.1",
    "sentence-transformers>=5.1.1",
    "spacy>=3.8.7",
    "youtube-transcript-api>=1.2.3",
]
